name        = IRS Careers Website - Default Layout
description = Default layout and template for IRS Careers Website.
template    = default

; ========================================
; Regions
; ========================================

; Header
regions[user_first]    = User Bar First
regions[user_second]   = User Bar Second
regions[branding]      = Branding
regions[navigation]    = Navigation
regions[header_first]  = Header First
regions[header_second] = Header Second

; Content
regions[preface_first]     = Preface First
regions[preface_second]    = Preface Second
regions[preface_third]     = Preface Third
regions[highlighted]       = Highlighted
regions[help]              = Help
regions[sidebar_first]     = First Sidebar
regions[content]           = Content
regions[sidebar_second]    = Second Sidebar
regions[postscript_first]  = Postscript First
regions[postscript_second] = Postscript Second
regions[postscript_third]  = Postscript Third
regions[postscript_fourth] = Postscript Fourth

; Footer
regions[footer_first] = Footer First
regions[footer_second]= Footer Second
