<?php

define('IRS_FITCHECK_CONTENT', 'irs_calculator_fitcheck_content');
define('IRS_FITCHECK_QUESTIONS', 'irs_calculator_fitcheck_questions');
define('IRS_EXPERIENCE_QUESTIONS', 'irs_calculator_experience_questions');

//include('irs_calculators.install');
//irs_calculators_install();

// Implementation of hook_menu()
function irs_calculators_menu() {

  $items = array();

  $items ['admin/config/irsjobs'] = array(
    'title' => 'IRS Careers', 
    'description' => 'Custom functionalities for the IRS Careers web application.', 
    'position' => 'right', 
    'page callback' => 'system_admin_menu_block_page', 
    'access arguments' => array(
      'administer site configuration' 
      ), 
    'file' => 'system.admin.inc', 
    'file path' => drupal_get_path( 'module', 'system' ) 
  );

  $items['admin/config/irsjobs/calculators/fit-check'] = array(
    'title' => 'Fit Check Calculator',
    'description' => 'Configuration for the Fit Check calculator.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('irs_calculator_fitcheck_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/irs_calculators.fitcheck.admin.inc',
    'type' => MENU_NORMAL_ITEM,
    'weight' => 20
  );

  // Theme configuration subtabs.
  $items['admin/config/irsjobs/calculators/fit-check/content-results'] = array(
    'title' => 'Content & Answers',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );

  // Theme configuration subtabs.
  $items['admin/config/irsjobs/calculators/fit-check/questions'] = array(
    'title' => 'Questions',
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('irs_calculator_fitcheck_admin_questions_form'),
    'file' => 'includes/irs_calculators.fitcheck.admin.inc',
  );

  $items['admin/config/irsjobs/calculators/experience'] = array(
    'title' => 'Experience Calculator',
    'description' => 'Configuration for the Experience calculator.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('irs_calculator_experience_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'includes/irs_calculators.experience.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function irs_calculators_block_info() {
  $blocks = array();

  $blocks['fit_check'] = array(
    'info' => 'Fit Check Calculator',
  );

  $blocks['experience'] = array(
    'info' => 'Experience Calculator',
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function irs_calculators_block_configure($delta = '') {
  $form = array();

  switch ($delta) {
    case 'fit_check' :
      break;

    case 'experience' :
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function irs_calculators_block_save($delta = '', $edit = array()) {
}

/**
 * Implement hook_block_view_alter
 */
function irs_calculators_block_view_alter(&$data, $block) {
}

/**
 * Implements hook_block_view().
 */
function irs_calculators_block_view($delta = '') {
  $values = variable_get(IRS_FITCHECK_CONTENT);

  // Path to this module
  $path = drupal_get_path('module', 'irs_calculators');

  // Set the block rendered array
  $block = array();

  switch ($delta) {
    case 'experience' :

      $block = array
      (
        'content' => array
        (
          '#markup' => irs_calculators_experience_markup(),
          '#attached' => array
          (
            'css' => array($path . '/assets/irs_calculators-experience.css'),
            'js' => array($path . '/assets/irs_calculators-experience.js'),
          ),
        ),
      );

      break;

    case 'fit_check' :

      $block = array
      (
        'content' => array
        (
          '#markup' => irs_calculators_fitcheck_markup(),
          '#attached' => array
          (
            'css' => array($path . '/assets/irs_calculators-fitcheck.css'),
            'js' => array($path . '/assets/irs_calculators-fitcheck.js'),
          ),
        ),
      );

      break;
  }

  return $block;
}

/**
 * Create the Experience Block Markup
 *
 *
 */
function irs_calculators_experience_markup() {
  $markup = '';

  require('includes/irs_calculators.experience.admin.inc');

  // Get the necessary fields and values
  $fields = irs_calculator_experience_fields();
  $values = variable_get(IRS_EXPERIENCE_QUESTIONS);

  // Set main markup
  $start_title = $values['content']['title'];
  $start_body = $values['content']['body'];

  // Build out questions
  $questions_html = '';

  foreach ($fields as $field_name => $field_row) {
    $question_title = $values[$field_name]['title'];

    // Build the options
    $question_body = '';
    $options_html = '';
    $conditions_html = '';

    if (isset($values[$field_name]['body'])){
      $question_body = str_replace(array_keys($values[$field_name]['inputs']), $values[$field_name]['inputs'], $values[$field_name]['body']);
    }

    $question_class = (isset($values[$field_name]['type']) && $values[$field_name]['type'] == 'question-condition') ? 'question-condition' : '';

    foreach ($values[$field_name]['options'] as $option_key => $option_row){
        $trigger_field = (isset($values[$field_name]['trigger-field'])) ? $values[$field_name]['trigger-field'] : '';
        $trigger_data = ($trigger_field != '') ? 'data-trigger="'.$trigger_field.'"' : '';
        $trigger_values = ($trigger_field != '') ? 'data-trigger-values="'.implode(',',$option_row['trigger']).'"' : '';
        $option_title = $option_row['title'];

        // Add in any conditions for the option (check against grades)
        if (isset($option_row['condition'])){
          foreach ($option_row['condition'] as $condition_index => $condition){
            // Get condition values
            $body = $condition['body'];
            $type = $condition['type'];
            $value = $condition['value'];

            // Build condition html
            $current_html = '<div class="option-condition" data-condition-option="'.$option_key.'" data-condition-type="'.$type.'" data-condition-value="'.$value.'">'.$body.'</div>';

            // Replace any inputs for tokens
            if (isset($condition['inputs'])){
              $current_html = str_replace(array_keys($condition['inputs']), $condition['inputs'], $current_html);
            }

            $conditions_html .= $current_html;
          }
        }

        switch($field_row['input']){
          case 'text':
            $options_html .= '<div class="option" data-option-id="'.$option_key.'"><span class="title">'.$option_title.'</span> <input type="text" name="'.$option_key.'" value="" '.$trigger_data . $trigger_values .' /></div>';
            break;
          case 'radio':
            $options_html .= '<div class="option" data-option-id="'.$option_key.'"><input type="radio" name="'.$field_name.'" value="'.$option_key.'" '.$trigger_data . $trigger_values . ' /> <span class="title">'.$option_title.'</span></div>';
            break;
        }
    }

    $questions_html .= <<<QUESTIONS
      <div class="question $field_name $question_class">
        <div class="title">$question_title</div>
        <div class="body">$question_body</div>
        <div class="options">
          $options_html
        </div>
        <div class="conditions">
          $conditions_html
        </div>
      </div>
QUESTIONS;
  }

  // Build the Markup for the HTML
  $markup = <<<HTML
    <div id="experience-calculator">
        <div class="content">
            <h2>$start_title</h2>
            <div class="body">$start_body</div>
        </div>
        $questions_html
        <div class="buttons">
            <a href="#" data-current="0" data-action="calculate" class="button">Calculate</a>
        </div>
    </div>
HTML;

  // Quick fix to attach the stylesheet
  $stylesheet = '<style>' . file_get_contents(dirname(__FILE__) . '/assets/irs_calculators-experience.css') . '</style>';

  return $stylesheet . $markup;
}

/**
 * Create the FitCheck Block Markup
 *
 * @todo  Figure out why css is not attaching in irs_calculators_block_view
 * @return string
 */
function irs_calculators_fitcheck_markup() {
  require(dirname(__FILE__) . '/includes/irs_calculators.fitcheck.admin.inc');

  // Get the necessary fields and values
  $result_fields = irs_calculator_fitcheck_fields();
  $result_values = variable_get(IRS_FITCHECK_CONTENT);

  $question_fields = irs_calculator_fitcheck_question_fields();
  $question_values = variable_get(IRS_FITCHECK_QUESTIONS);

  // Default start variables
  $start_title = $result_values['title']['body'];
  $start_body = $result_values['body']['body'];

  // Prepare the Result Divs for output
  $result_html = '';
  $more_info_text = 'More information about ';
  $counter = 0;

  foreach ($result_fields as $field_name => $field_title){
    if (!is_array($field_title)){
      $result_heading = $result_values[$field_name]['heading'];
      $result_body = $result_values[$field_name]['body'];
      $result_moreinfo_url = $result_values[$field_name]['more-info-url'];

      $result_moreinfo = t($more_info_text . $field_title);
      if (!empty($result_moreinfo_url)){
        $result_moreinfo = l($result_moreinfo, $result_moreinfo_url);
      }

      $result_html .= <<<MESSAGE
        <div id="$field_name" class="result" data-result-id="$counter">
          <div class="heading">$result_heading</div>
          <div class="body">$result_body</div>
          <div class="more-info-url">$result_moreinfo</div>
          <div class="apply"><a href="http://jobs.irs.gov/USAJOBS/" class="button ignore" target="_blank">Search & Apply</a></div>
        </div>
MESSAGE;

      $counter++;
    }
  }

  // Prepare the Question Divs for output
  $questions_html = '';
  $previous_button = '<a href="#" class="button" data-action="back">Back</a>';
  $next_button = '<a href="#" class="button" data-action="next">Next</a>';
  $submit_button = '<a href="#" class="button" data-action="submit">Submit</a>';
  $counter = 0;
  $total = count($question_fields) - 1;

  foreach ($question_fields as $field_name => $field_title) {
    // Set the default pointer to the value and then set the question title
    $question_vals = $question_values[$field_name];
    $question_title = $question_vals['question'];

    // Create the html for the question options
    $options = '';
    foreach ($question_vals['options'] as $option_key => $option){
      $option_title = $option['title'];
      $option_weight = $option['weight'];

      $buttons = ($counter == 0) ? $previous_button . $next_button : (($counter < $total) ? $previous_button . $next_button : $submit_button);

      $options .= <<<OPTIONS
        <div class="option">
          <input type="radio" name="$field_name"  value="$option_weight" />
          $option_title
        </div>
OPTIONS;
    }

    // Set the index and take into account the start
    $index = $counter + 1;

    // Create the html output for the questions
    $questions_html .= <<<QUESTIONS
      <div class="question" data-index="$index">
        <div class="title">$question_title</div>
        <div class="options">
          $options
        </div>
        <div class="buttons">
          $buttons
        </div>
      </div>
QUESTIONS;

    $counter++;
  }


  // Build the Markup for the HTML
  $markup = <<<HTML
    <div id="fit-check-calculator">
        <h2>$start_title</h2>
        <div id="fit-check-start" data-index="0" class="question start">
            <div id="fit-check-body">$start_body</div>
            <div class="buttons">
                <a href="#" data-current="0" data-action="next" class="button" id="career-path-start">Click to Start</a>
            </div>
        </div>
        $questions_html
        $result_html
    </div>
HTML;

  // Quick fix to attach the stylesheet
  $stylesheet = '<style>' . file_get_contents(dirname(__FILE__) . '/assets/irs_calculators-fitcheck.css') . '</style>';


  return $stylesheet . $markup;
}